use click to manage cli (#33)
* [#32] Use click to manage cli options

This will allow us to inform the user when an unknown flag is used,
and also a lot of other functionality becomes available for free.

(Usage info, validation of args etc)

I took the liberty of using setuptools so that we could specify
click as a requirement using `install_requires`

* [#32] Get click to validate --path is existing dir

We can use click to ensure that the value of --path is a directory,
and it exists.

Without it, the old behaviour just gives a messy stacktrace.

But with this change, we can get a nicer erroe message

```
$ roamer --path tox.ini
Usage: main.py [OPTIONS]
Try "main.py --help" for help.

Error: Invalid value for "--path": Directory "tox.ini" is a file.
```

```
$ roamer --path 404
Usage: main.py [OPTIONS]
Try "main.py --help" for help.

Error: Invalid value for "--path": Directory "404" does not exist.
```

* Fix pylint wrong-import-order issue

* Tell pylint to ignore odd but correct code